### ISSUE TITLE
Move system level initialization code out of design.js and into intro.js

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#10]
Specifically the non-problem dependent, system initialization code.

**Comment by 1fifoto** [comment]
I would keep the number of globals down, so no; however I think we also need a default scaling denominator, SCLDEN_DEFAULT = 1.0/(FIX_WT*ZERO_WT);

**Comment by grumpyinca** [comment]
10 Non-problem dependent, system initialization code moved from design.js to intro.js.
