### ISSUE TITLE
Feedback on current state of list command implementation

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#15]
1. The response to an empty command line seems to produce an extra prompt:
PCyl>
PCyl: 
PCyl>
Perhaps this is part of a feature that echoes command input.

1. The state variable "area" is missing from some of the responses.  For example:
list dep
DEPENDENT VARIABLES                                        CONSTRAINT LEVELS
                                            STATUS         MIN           MAX
force           =      251.3274  LBS.                   1000.0000              
stress          =     2500.0000  PSI                                  3000.0000

1. A list command followed by multiple (DPSV) names separated by a single space produces expected results.  A list command followed by the same set of names separated by multiple blanks produces unexpected results.

1.  For this case, the term in parens should be "outputs":
PCyl>list state
PCyl: list state
DEPENDENT VARIABLES  (inputs)                        
force           =      251.3274  LBS.                      0.0000
area            =        0.5027  SQ.-IN.                   0.0000
stress          =     2500.0000  PSI                       0.0000
PCyl>

1.  "list levels" does not produce a listing of constraint levels.

1. The first design parameter in the listing produced by "list design" has an extra blank space in the "BEFORE SEARCH" column.
PCyl>list design
PCyl: list design
INDEPENDENT VARIABLES  (inputs)                       BEFORE SEARCH
pressure        =      500.0000  LBS/SQ-IN                  0.0000
radius          =        0.4000  INCH                      0.0000
thickness       =        0.0400  INCH                      0.0000
PCyl>

**Comment by 1fifoto** [comment]
1. Fixed. Removed input echo.
2. The 'area' has lmin = 0 and lmax = 0, so it should not print. No change.
3. Fixed. Added regular expression for multiple blanks.
4. Fixed. Changed from 'inputs' to 'outputs'. Copy-and-paste error.
5. The "list level" DOS PCyl output matches. No change.
6. The "LBS/SQ-IN" is 9 characters. No change.

**Comment by grumpyinca** [comment]
Per phone conversation: decided to keep echo of command input (1. above) at least for the duration of software development and testing.
