### ISSUE TITLE
PL/I code behavior investigation

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#21]
1.  List levels does not display full set of constraint levels.

2.  List dependent displays a value for area where reading the PL/I code and execution of the JS code suggests that it shouldn't.

**Comment by 1fifoto** [comment]
For # 2 above, the code is

     do i= 1 to k;
     im=i+n;
     if targfile=checkpt
      | ioopt >= svclass(i)
      | ioopt >= 4
       | lmin(im) ^= FREESTAT
       | lmax(im) ^= FREESTAT
       then call putdpsv(st_var_name(i),x(i),st_var_unit(i),im,obj);
     end;

And ioopt is 5 in our testing input file (in.txt), 

    set ioopt 5

and that is why area is displayed, because 'ioopt >= 4' causes it to print.

**Comment by 1fifoto** [comment]
The same is true for # 1 above. The code is:

     do i=1 to n;
     if  targfile=checkpt
       | ioopt >= dpclass(i)
       | ioopt >= 4
       | lmin(i) ^= FREESTAT
       | lmax(i) ^= FREESTAT
        then call putdpsv(parm_name(i),p(i),parm_unit(i),i,obj);
     end;

So that is why both list outputs differ between JS and PLI. 

Please close if you agree.

**Comment by grumpyinca** [comment]
I observe that the DOS PL/I version produces a value for area regardless of the value of ioopt.  This is true for list dep, list state & list var.  Note that in the JS STARTUP.DSN file, ioclass is set the same (=0) for all the design parameters.  I believe that the condition "| ioopt >= svclass(i)" is the one that causes area to appear in the output even though it has no constraints.

In summary, I agree that implementing ioopt in the JS code (see issue xx) will align operation of the two versions and make this particular mystery disappear.  Thus, I am closing this issue.  We should be sure to carefully inspect the results after ioopt is implemented.
