### ISSUE TITLE
Change command acknowledgement wrong for constraint levels

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#37]
It appears that the problem is only in the acknowledgement; not in the value that is set for constraint levels.

The may be a good time to confirm that parseFloat() is also applied to constants and any other appropriate places in the change.js module.

    **********************************************
    ***  Welcome to PCyl Version 1.2
    **********************************************
    PCyl: change thick max 0.155
    change thick max 0.155
    THICKNESS MAXIMUM CHANGED TO         0.0000   INCH
    PCyl: change stress max 7000.1
    change stress max 7000.1
    STRESS MAXIMUM CHANGED TO         0.0000   PSI
    PCyl: 
    PCyl: list thick

    list thick
    THICKNESS       =        0.0400  INCH                      0.0000        0.1550
    PCyl: list stress
    list stress
    STRESS          =     2500.0000  PSI                                  7000.1000
    PCyl:

**Comment by 1fifoto** [comment]
Merged into master, closing
