### ISSUE TITLE
NaN in output after fix of DP and search

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#38]
See last part of session output.

    **********************************************
    ***  Welcome to PCyl Version 1.2
    **********************************************
    PCyl: fix radius 0.444
    fix radius 0.444
    RADIUS IS FIXED AT         0.4440   INCH
    PCyl: search
    search
    SEARCH:    OBJ =          0.476569
    RETURN ON:      OBJ =           0.002707
    THE RESULT IS NOT FEASIBLE.
             YOU NEED TO DO A LITTLE MORE WORK ON THIS DESIGN.
             REFER TO THE DOCUMENTATION SECTION ON  "FEASIBILITY"  FOR SUGGESTIONS.
    CONSTRAINT VIOLATIONS
                            VALUE        LEVEL     DIFFERENCE    PERCENT
    PRESSURE        MAX    1552.8056    1500.0000     52.8056      3.5204  VIOLATED
    FORCE           MIN     961.6851    1000.0000     38.3149      3.8315  VIOLATED
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.002707
    PCyl: list both
    list both
    INDEPENDENT VARIABLES                                      CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    PRESSURE        =     1552.8056  LB/SQ-IN                             1500.0000
    RADIUS          =        0.4440  INCH       FIXED          0.4440        0.4440
    THICKNESS       =          -NaN  INCH                      0.0000        0.0500
    DEPENDENT VARIABLES                                        CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    FORCE           =      961.6851  LBS.                   1000.0000              
    STRESS          =          -NaN  PSI                                  3000.0000
    PCyl:

**Comment by grumpyinca** [comment]
Second case:

    **********************************************
    ***  Welcome to PCyl Version 1.2
    **********************************************
    PCyl: list both
    list both
    INDEPENDENT VARIABLES                                      CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    PRESSURE        =      500.0000  LB/SQ-IN                             1500.0000
    RADIUS          =        0.4000  INCH                      0.0000        0.5000
    THICKNESS       =        0.0400  INCH                      0.0000        0.0500
    DEPENDENT VARIABLES                                        CONSTRAINT LEVELS
                                            STATUS         MIN           MAX
    FORCE           =      251.3274  LBS.                   1000.0000              
    STRESS          =     2500.0000  PSI                                  3000.0000
    PCyl: fix pressure 700
    fix pressure 700
    PRESSURE IS FIXED AT       700.0000   LB/SQ-IN
    PCyl: l viol
    l viol
    l viol ? ?
    PCyl: list viol
    list viol
    CONSTRAINT VIOLATIONS
                            VALUE        LEVEL     DIFFERENCE    PERCENT
    FORCE           MIN     351.8584    1000.0000    648.1416     64.8142  VIOLATED
    STRESS          MAX    3500.0000    3000.0000    500.0000     16.6667  VIOLATED
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.447865
    PCyl: search
    search
    SEARCH:    OBJ =          0.447865
    RETURN ON:      OBJ =           0.000000
    THE RESULT IS  FEASIBLE.
             THIS DESIGN MEETS ALL STATED REQUIREMENTS (CONSTRAINTS).
             YOU MAY BE ABLE TO IMPROVE IT WITH THE SEEK COMMAND.
    INDEPENDENT VARIABLES                                      CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    PRESSURE        =      700.0000  LB/SQ-IN   FIXED        700.0000      700.0000
    RADIUS          =          -NaN  INCH                      0.0000        0.5000
    THICKNESS       =        0.0499  INCH                      0.0000        0.0500
    PCyl:

**Comment by 1fifoto** [comment]
Merged into master, closing.
