### ISSUE TITLE
Add support for return codes from Pattern Search  (NCODE)

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#46]
*  The information is valuable  to the user
*  The output comparisons performed as part of testing will have one less point of difference.

**Comment by 1fifoto** [comment]
Branch 46 "Add support for return codes from Pattern Search (NCODE)" committed and pushed upstream. Awaiting release 0.4 tagging

**Comment by 1fifoto** [comment]
Merged into master, closing
