### ISSUE TITLE
Implement 15 of 16 sub-commands of List command

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/pcyl#6]
Defer:  INTERNAL sub-command; Defer:  Pause procedure; Defer?: output to print file (checkpt)

**Comment by grumpyinca** [comment]
Make response to a LIST command that has no arguments similar to the response produced by the PL/I code: 
PCyl: list

LIST:
ENTER MODIFIERS INDICATING OUTPUT DESIRED.
POSSIBLE MODIFIERS ARE:
   ALL,  INDEPENDENT,  DEPENDENT,  BOTH_I&D,  VIOLATIONS,  DESIGN,  
   PARAMETERS,  STATE,  VARIABLES,  CONSTANTS,  SATISFIED,  OBJECTIVE,  
   LEVELS,  FIXED,  LABEL,  INTERNAL

PCyl:

**Comment by grumpyinca** [comment]
More samples of PL/I LIST command output ... 
  (note ... looks better with fixed spacing font)
  (note … constraint levels are included)
  (also note … these are the state variable values for the default STARTUP.DSN.
   The value of FORCE is off in the 6th digit; area and stress are identical to the limit of the format):

PCyl: list radius area stress pi


RADIUS          =        0.4000  INCH                     0.0000        0.5000
AREA            =        0.5027  SQ.-IN.         
STRESS          =     2500.0000  PSI                                 3000.0000
PI              =        3.1416  _       

PCyl: 


PCyl: list both



INDEPENDENT VARIABLES                                     CONSTRAINT LEVELS
                                           STATUS         MIN           MAX
PRESSURE        =      500.0000  LBS/SQ-I                            1500.0000
RADIUS          =        0.4000  INCH                     0.0000        0.5000
THICKNESS       =        0.0400  INCH                     0.0000        0.0500

FORCE           =      251.3273  LBS.                  1000.0000
AREA            =        0.5027  SQ.-IN.         
STRESS          =     2500.0000  PSI                                 3000.0000

PCyl:

**Comment by 1fifoto** [comment]
Thanks!

**Comment by 1fifoto** [comment]
I need more output samples for each of the 15 subcommands (you gave me BOTH above so you can skip that one): ALL, INDEPENDENT, DEPENDENT, ~~BOTH_I&D~~, VIOLATIONS, DESIGN, PARAMETERS, STATE, VARIABLES, CONSTANTS, SATISFIED, OBJECTIVE, LEVELS, FIXED, LABEL, INTERNAL. Even though LABEL and INTERNAL need not be done I'd like to see sample output of them.

Here is my current output:

    **********************************************
    ***  Welcome to PCyl Version 1.2
    **********************************************
    PCyl>list all
    INDEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    pressure = 500 LBS/SQ-IN FIXED 0 1500
    radius = 0.4 INCH FIXED 0 0.5
    thickness = 0.04 INCH FIXED 0 0.05
    DEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    force = 251.32741228718348 LBS. FIXED 1000
    stress = 2500 PSI FIXED 0 3000
    CONSTANTS
    pi = 3.141592653589793
    CONSTRAINT VIOLATIONS VALUE LEVEL DIFFERENCE PERCENT
    force  =  251.32741228718348 1000 748.6725877128165 74.86725877128166 LBS.
    stress  =  2500 0 0 0 PSI
    PCyl>list independent
    INDEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    pressure = 500 LBS/SQ-IN FIXED 0 1500
    radius = 0.4 INCH FIXED 0 0.5
    thickness = 0.04 INCH FIXED 0 0.05
    PCyl>list dependent
    DEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    force = 251.32741228718348 LBS. FIXED 1000
    stress = 2500 PSI FIXED 0 3000
    PCyl>list both
    INDEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    pressure = 500 LBS/SQ-IN FIXED 0 1500
    radius = 0.4 INCH FIXED 0 0.5
    thickness = 0.04 INCH FIXED 0 0.05
    DEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    force = 251.32741228718348 LBS. FIXED 1000
    stress = 2500 PSI FIXED 0 3000
    PCyl>list violations
    NO CONSTRAINTS ARE VIOLATED
    PCyl>list design
    INDEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    pressure = 500 LBS/SQ-IN FIXED 0 1500
    radius = 0.4 INCH FIXED 0 0.5
    thickness = 0.04 INCH FIXED 0 0.05
    PCyl>list parameters
    INDEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    pressure = 500 LBS/SQ-IN FIXED 0 1500
    radius = 0.4 INCH FIXED 0 0.5
    thickness = 0.04 INCH FIXED 0 0.05
    PCyl>list state
    DEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    force = 251.32741228718348 LBS. FIXED 1000
    stress = 2500 PSI FIXED 0 3000
    PCyl>list variables
    DEPENDENT VARIABLES CONSTRAINT LEVELS STATUS   MIN     MAX
    force = 251.32741228718348 LBS. FIXED 1000
    stress = 2500 PSI FIXED 0 3000
    PCyl>list constants
    CONSTANTS
    pi = 3.141592653589793
    PCyl>list satisfied
    NO CONSTRAINTS ARE VIOLATED
    force  =  251.32741228718348 1000 0 0 LBS.
    stress  =  2500 0 0 0 PSI
    PCyl>list objective
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS: 0
    PCyl>list levels
    THERE ARE NO 
    FUNCTIONALLY DETERMINED CONSTRAINT LEVELS:
    (REFER TO DOCUMENTATION SECTION  "FUNCTION".)
    CONSTRAINT ON:           IS CURRENT VALUE OF: ----------------         -------------------
    PCyl>list fixed
    NO VARIABLES HAVE "FIXED" STATUS.
    PCyl>list labels
    labels ? ?
    PCyl>list label
    List label is not yet implemented.
    PCyl>list internal
    List intenal is not yet implemented.L
    PCyl>quit
    Quitting ...

**Comment by 1fifoto** [comment]
I think it might be a good idea to walk through this code so I can get your feedback about my conversion from PLI

**Comment by 1fifoto** [comment]
![screen shot 2018-06-17 at 9 03 22 am](https://user-images.githubusercontent.com/1581602/41509987-760af330-7222-11e8-9ca2-c33449aa38b6.png)
![screen shot 2018-06-17 at 9 03 41 am](https://user-images.githubusercontent.com/1581602/41509988-8219b062-7222-11e8-8e2f-233284a0b2ba.png)
![screen shot 2018-06-17 at 9 03 52 am](https://user-images.githubusercontent.com/1581602/41509989-82583c10-7222-11e8-867a-fe92946e8fc5.png)
![screen shot 2018-06-17 at 9 04 05 am](https://user-images.githubusercontent.com/1581602/41509990-826bfd4a-7222-11e8-9773-31d73df8fc60.png)
![screen shot 2018-06-17 at 9 04 16 am](https://user-images.githubusercontent.com/1581602/41509991-827e6ca0-7222-11e8-9ad5-ed72355198da.png)
![screen shot 2018-06-17 at 9 04 30 am](https://user-images.githubusercontent.com/1581602/41509992-828fd86e-7222-11e8-8dfc-62672714128a.png)
![screen shot 2018-06-17 at 9 04 39 am](https://user-images.githubusercontent.com/1581602/41509993-82a2607e-7222-11e8-934f-b8e7c84618c6.png)
![screen shot 2018-06-17 at 9 04 54 am](https://user-images.githubusercontent.com/1581602/41509994-82b2135c-7222-11e8-94d2-9d2e1c8e1cc6.png)
![screen shot 2018-06-17 at 9 05 03 am](https://user-images.githubusercontent.com/1581602/41509995-82d07be4-7222-11e8-89cf-16d95a803227.png)
![screen shot 2018-06-17 at 9 05 13 am](https://user-images.githubusercontent.com/1581602/41509996-82e4ac72-7222-11e8-86e0-0edd05d2fc39.png)
![screen shot 2018-06-17 at 9 05 30 am](https://user-images.githubusercontent.com/1581602/41509997-832835a0-7222-11e8-8259-bc3ce7571695.png)

**Comment by 1fifoto** [comment]
Here is a the current output, which mostly matches, except for prompting and blank lines

    **********************************************
    ***  Welcome to PCyl Version 1.2
    **********************************************
    START:
      The START command is not yet fully implemented.
    count: NFIXED, NSTF, NFDCL =  0 0 0
    start: NFIXED, NSTF, NFDCL =  0 0 0
    PCyl>PCyl: 
    PCyl>PCyl: list
    LIST:
    ENTER MODIFIERS INDICATING OUTPUT DESIRED.
    POSSIBLE MODIFIERS ARE:
       all, independent, dependent, both_i&d, violations, design
       parameters, state, variables, constants, satisfied, objective
       levels, fixed, label, internal
    PCyl>PCyl: list junk
    junk ? ?
    LIST:
    ENTER MODIFIERS INDICATING OUTPUT DESIRED.
    POSSIBLE MODIFIERS ARE:
       all, independent, dependent, both_i&d, violations, design
       parameters, state, variables, constants, satisfied, objective
       levels, fixed, label, internal
    PCyl>PCyl: list radius area stress pi
    radius          =        0.4000  INCH                      0.0000        0.5000
    area            =        0.5027  SQ.-IN.                                       
    stress          =     2500.0000  PSI                                  3000.0000
    pi              =        3.1416  _       
    PCyl>PCyl: list all
    LABEL is not implemented yet
    CONSTANTS
    pi              =        3.1416  _       
    INDEPENDENT VARIABLES                                      CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    pressure        =      500.0000  LBS/SQ-IN                             1500.0000
    radius          =        0.4000  INCH                      0.0000        0.5000
    thickness       =        0.0400  INCH                      0.0000        0.0500
    DEPENDENT VARIABLES                                        CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    force           =      251.3274  LBS.                   1000.0000              
    stress          =     2500.0000  PSI                                  3000.0000
    NO VARIABLES HAVE "FIXED" STATUS.
    THERE ARE NO FUNCTIONALLY DETERMINED CONSTRAINT LEVELS:
    (REFER TO DOCUMENTATION SECTION  "FUNCTION".)
    CONSTRAINT VIOLATIONS
                            VALUE        LEVEL     DIFFERENCE    PERCENT
    pressure        MAX     500.0000    1500.0000   1000.0000    -66.6667  
    radius          MIN       0.4000       0.0000      0.4000   -100.0000  
    radius          MAX       0.4000       0.5000      0.1000    -20.0000  
    thickness       MIN       0.0400       0.0000      0.0400   -100.0000  
    thickness       MAX       0.0400       0.0500      0.0100    -20.0000  
    force           MIN     251.3274    1000.0000    748.6726     74.8673  VIOLATED
    stress          MAX    2500.0000    3000.0000    500.0000    -16.6667  
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.560511
    INDEPENDENT VARIABLES  (inputs)                       BEFORE SEARCH
    pressure        =      500.0000  LBS/SQ-IN                  0.0000
    radius          =        0.4000  INCH                      0.0000
    thickness       =        0.0400  INCH                      0.0000
    DEPENDENT VARIABLES  (inputs)                        
    force           =      251.3274  LBS.                      0.0000
    area            =        0.5027  SQ.-IN.                   0.0000
    stress          =     2500.0000  PSI                       0.0000
    INTERNAL VARIABLES is not implemented yet
    PCyl>PCyl: list independent
    INDEPENDENT VARIABLES                                      CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    pressure        =      500.0000  LBS/SQ-IN                             1500.0000
    radius          =        0.4000  INCH                      0.0000        0.5000
    thickness       =        0.0400  INCH                      0.0000        0.0500
    PCyl>PCyl: list dependent
    DEPENDENT VARIABLES                                        CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    force           =      251.3274  LBS.                   1000.0000              
        stress          =     2500.0000  PSI                                  3000.0000
    PCyl>PCyl: list both
    INDEPENDENT VARIABLES                                      CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    pressure        =      500.0000  LBS/SQ-IN                             1500.0000
    radius          =        0.4000  INCH                      0.0000        0.5000
    thickness       =        0.0400  INCH                      0.0000        0.0500
    DEPENDENT VARIABLES                                        CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    force           =      251.3274  LBS.                   1000.0000              
    stress          =     2500.0000  PSI                                  3000.0000
    PCyl>PCyl: list violations
    CONSTRAINT VIOLATIONS
                            VALUE        LEVEL     DIFFERENCE    PERCENT
    force           MIN     251.3274    1000.0000    748.6726     74.8673  VIOLATED
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.560511
    PCyl>PCyl: list design
    INDEPENDENT VARIABLES  (inputs)                       BEFORE SEARCH
    pressure        =      500.0000  LBS/SQ-IN                  0.0000
    radius          =        0.4000  INCH                      0.0000
    thickness       =        0.0400  INCH                      0.0000
    PCyl>PCyl: list parameters
    INDEPENDENT VARIABLES  (inputs)                       BEFORE SEARCH
    pressure        =      500.0000  LBS/SQ-IN                  0.0000
    radius          =        0.4000  INCH                      0.0000
    thickness       =        0.0400  INCH                      0.0000
    PCyl>PCyl: list state
    DEPENDENT VARIABLES  (inputs)                        
    force           =      251.3274  LBS.                      0.0000
    area            =        0.5027  SQ.-IN.                   0.0000
    stress          =     2500.0000  PSI                       0.0000
    PCyl>PCyl: list variables
    DEPENDENT VARIABLES  (inputs)                        
    force           =      251.3274  LBS.                      0.0000
    area            =        0.5027  SQ.-IN.                   0.0000
    stress          =     2500.0000  PSI                       0.0000
    PCyl>PCyl: list constants
    CONSTANTS
    pi              =        3.1416  _       
    PCyl>PCyl: list satisfied
    CONSTRAINT SATISFACTIONS
                            VALUE        LEVEL     DIFFERENCE    PERCENT
    pressure        MAX     500.0000    1500.0000   1000.0000    -66.6667  
    radius          MIN       0.4000       0.0000      0.4000   -100.0000  
    radius          MAX       0.4000       0.5000      0.1000    -20.0000  
    thickness       MIN       0.0400       0.0000      0.0400   -100.0000  
    thickness       MAX       0.0400       0.0500      0.0100    -20.0000  
    stress          MAX    2500.0000    3000.0000    500.0000    -16.6667  
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.560511
    PCyl>PCyl: list objective
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.560511
    PCyl>PCyl: list levels
    THERE ARE NO FUNCTIONALLY DETERMINED CONSTRAINT LEVELS:
    (REFER TO DOCUMENTATION SECTION  "FUNCTION".)
    PCyl>PCyl: list fixed
    O VARIABLES HAVE "FIXED" STATUS.
    PCyl>PCyl: list label
    LABEL is not implemented yet
    PCyl>PCyl: list internal
    INTERNAL VARIABLES is not implemented yet
    PCyl>PCyl: quit
    Quitting ...

**Comment by 1fifoto** [comment]
By the way, this took a lot more work to get the output to match. At this time I think you got the easier deal by focusing on START command. Ha!
