### ISSUE TITLE
Update test files (in.txt, expected_dos.txt, etc.) - part tri

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/pcyl#69]

**Comment by 1fifoto** [comment]
![screen shot 2018-07-02 at 10 38 23 pm](https://user-images.githubusercontent.com/1581602/42197491-a7a65fa6-7e48-11e8-9a3a-143bdbb0b8e1.png)

**Comment by grumpyinca** [comment]
Test files in branch 69 pushed to remote, merged into master and pushed to remote (origin/master).  Closing issue.
