### ISSUE TITLE
Convert remainder of Help text for PCYL (ignoring SpringSys help text until later)

### ISSUE THREAD

**Issue by 1fifoto** [thegrumpys/pcyl#71]
The current list of Help items are:

1. COMMANDS - done
1. CHANGE - done
1. EXECUTE - done
1. FIX - done
1. FREE - done
1. HELP - done
1. LIST - done
1. QUIT - done
1. REPORT - done
1. SAVE - done
1. SEARCH - done
1. SEARCH1 - done
1. SEEK - done
1. SEEK_OVERVIEW - done
1. SELECT - done
1. SET - done
1. START - done
1. TRADE - done
1. TRADE_OVERVIEW - done
1. FEATURES
1. INTRODUCTION
1. TUTORIAL
1. GETTING_STARTED
1. NOTATION
1. TERMINOLOGY
1. CONSTRAINT_OVIEW
1. SPRING_BASICS
1. REFERENCES
1. RESTRICTIONS
1. NAMES
1. C_NAMES
1. E_NAMES
1. FD_DIAGRAMS
1. SPR_CONSTRAINTS
1. FACTOR_OF_SAFETY2
1. MATERIALS
1. END_TYPES
1. BUCKLING
1. CYCLE_LIFE
1. WHAT_TO_DO_IF
1. DESIGN_TO_STRESS
1. PROP_CALC_METHOD
1. END_CALC_METHOD
1. FILES_ON_DISK
1. STARTUP.DSN
1. EQNSET1
1. EQNSET2
1. HOT_WOUND
1. METRIC
1. STD_WIRE_SIZE
1. CATALOGS
1. IT_RANGE
1. HOOK_STRESS
1. FEASIBILITY
1. FUNCTION
1. BACKUP
1. INSTALLATION
1. FUNCTION_KEYS
1. TRICKS
1. ERROR_RECOVERY
1. NEW_FEATURES
1. Y/N
1. @RUNID
1. @MENU
1. @TYPEMENU
1. @SLENDER
1. @PROCESS

**Comment by grumpyinca** [comment]
Mike please review for PCyl which additional help is needed. Tell me the numbers of which one I should import.

**Comment by grumpyinca** [comment]
Mike, please point me to the PLI file that is the best source of help text.

**Comment by grumpyinca** [comment]
Item 21:  Introduction  is in HELP1.DAT.  
             It needs work but is mostly useful as is.

Item 24:  Notation  is in HELP1.DAT

Item 25:  Terminology is in HELP1.DAT

Item 26:  Constraint_Oview  is in HELP1.DAT

Item 55:  Function  is in HELP3.DAT

Item 62:  Y/N  is in HELP5.DAT

**Comment by 1fifoto** [comment]
Merged into master, closing
