### ISSUE TITLE
Figure out why Mike's HELP has spurious "blanks"

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#72]
The spaces appear in pairs! Mike will tell Brian where two places in the help text this occurs on his system. See expected_out and expected_dos files for possible examples of this issue.

**Comment by grumpyinca** [comment]
The help file source may be found in PLISpringSys\CADSYS\MANUAL.  The files are named HELPxx.DAT.

**Comment by 1fifoto** [comment]
I do not see any discrepancies. Please show me where two case are in your output.

**Comment by grumpyinca** [comment]
If I open expected_out.txt in the Eclipse editor, I see the problem.  If I open the same expected_out.txt in GitHub's browser interface, I do **not** see the problem.

If I open a Windows command window, move to the pcyl directory and execute "node app.js".  I see the problem.  If I execute the program under Eclipse, I see the problem.

I have a hunch that this is system dependent.  Something like the cr versus crlf situation.  Thus, you may never be able to see the problem on a Mac.

**Comment by grumpyinca** [comment]
![image](https://user-images.githubusercontent.com/39974784/42407368-b7ba7e66-816f-11e8-92d8-29c68d48f747.png)

**Comment by grumpyinca** [comment]
The above screenshot is from the actual_out.txt file generated with the current master and the current in.txt file as displayed in the Eclipse editor.  You should be able to recreate and observe the same line numbers.

**Comment by 1fifoto** [comment]
Mystery solved! Spurious hex 00s in the file.
![screen shot 2018-07-07 at 7 17 05 am](https://user-images.githubusercontent.com/1581602/42410835-54708430-81b6-11e8-920a-2df8bc23078f.png)

**Comment by grumpyinca** [comment]
Confirmed that the fix is effective by pulling the latest version of master and then running app.js under Eclipse.  In addition, I executed "npm run coverage" and compared actual_out.txt to the previous version.  Closing the issue.
