### ISSUE TITLE
Investigate unexpected behavior of violations before & after use of TRADE

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#76]
The in.txt file for release 0.5 contains multiple comments:
"Pay attention to violation on FORCE before and after TRADE".
These comments are positioned around use of the TRADE command in the hope of facilitating this investigation.

In theory, the use of the TRADE command in the operation of the 0.5 in.txt file should reset everything to the state that existed before TRADE was invoked.  If you look at violations on FORCE, that may not have happened properly.  The behavior is observed in both the PLI (expected_dos.txt) and JavaScript (expected_out.txt) code.  Is there a bug in here somewhere ?

**Comment by grumpyinca** [comment]
I was able to reproduce the behavior under the Eclipse debugger.  It is possible to step through and watch the values of vmin by expanding sv.  As of this moment, I continue to believe that there is a problem with the reset of values when trade finishes without retaining the calculated result (i.e. something is not handled correctly in the case that trade attempts to set everything back to "oldvalue".  Again, note that the problem is also apparent in the PL/I code.  

However, since this investigation is turning into an extended effort.  I will defer further activity on this issue in order to make progress on other issues.

**Comment by 1fifoto** [comment]
Please include specifics of input and output so that I can reproduce this issue. For example an input file and screen shots before along with actual output and screen shots after. Since it appears on both, I’m only interested in the JS version to reduce the work to capture the issue.

**Comment by grumpyinca** [comment]
Multiple places in trade, change and fix found where a constraint level was being manipulated without a corresponding call to sclden() to update the scaling denominator.  These problems originated in the PL/I code. In the process, a similar but more recent coding error was found in trade.js.  This issue will be closed after a more careful inspection of expected_out.txt and expected_dos.txt

**Comment by grumpyinca** [comment]
Review of expected_out.txt and expected_dos.txt is now complete.  Closing.
