### ISSUE TITLE
Investigate need to improve FIX command validation

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#80]
fix <dp / sv> junk

does not produce an error message.  The result seems to be the same as if "junk" did not appear on the command line.  Considering the impending move to a browser-based GUI, is there any problem here ?

Note: in this situation, the PL/I code will get a conversion error and branch to the main command level.

**Comment by 1fifoto** [comment]
Added in error message: "INVALID OR NO VALUE GIVEN, ASSUMING CURRENT VALUE XXXXXXXXX.XXXX" for both Design Parameters and State Variables.

    PCyl: list both
    list both
    INDEPENDENT VARIABLES                                      CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    PRESSURE        =      500.0000  LB/SQ-IN                             1500.0000
    RADIUS          =        0.4000  INCH                      0.0000        0.5000
    THICKNESS       =        0.0400  INCH                      0.0000        0.0500
    DEPENDENT VARIABLES                                        CONSTRAINT LEVELS
                                                STATUS         MIN           MAX
    FORCE           =      251.3274  LBS.                   1000.0000              
    AREA            =        0.5027  SQ.-IN.                                       
    STRESS          =     2500.0000  PSI                                  3000.0000
    PCyl: fix radius junk
    fix radius junk
    INVALID OR NO VALUE GIVEN, ASSUMING CURRENT VALUE         0.4000
    RADIUS IS FIXED AT         0.4000   INCH
    PCyl: fix stress junk
    fix stress junk
    INVALID OR NO VALUE GIVEN, ASSUMING CURRENT VALUE      2500.0000
    STRESS IS A DEPENDENT VARIABLE.
    REMEMBER THAT A SEARCH WILL BE REQUIRED TO ESTABLISH THE DESIRED VALUE.
    STRESS IS FIXED AT      2500.0000   PSI
    PCyl: fix radius
    fix radius
    INVALID OR NO VALUE GIVEN, ASSUMING CURRENT VALUE         0.4000
    RADIUS IS FIXED AT         0.4000   INCH
    PCyl: fix stress
    fix stress
    INVALID OR NO VALUE GIVEN, ASSUMING CURRENT VALUE      2500.0000
    STRESS IS A DEPENDENT VARIABLE.
    REMEMBER THAT A SEARCH WILL BE REQUIRED TO ESTABLISH THE DESIRED VALUE.
    STRESS IS FIXED AT      2500.0000   PSI
    PCyl:

**Comment by 1fifoto** [comment]
Merged into master, closing
