### ISSUE TITLE
Investigate filename validation in start.js

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#81]
In release 0.5, the syntax:
  **start checkpt**
is handled correctly.  The syntax
  **start checkpt.dsn**
is not.

The PL/I code does the necessary validation to avoid the issue.  See the comparison of expected_dos.txt and expected_out.txt.

**Comment by 1fifoto** [comment]
Merged into master, closing

**Comment by 1fifoto** [comment]
One more time... merged into master, awaiting your review to close it.

**Comment by grumpyinca** [comment]
I compared an updated actual_out.txt with the immediately preceding expected_out.txt and observed the desired operation.  Closing.
