### ISSUE TITLE
Recent changes to list command not effective or not checked in

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#83]
Cut and paste from Slack conversation of ~2 days ago:

Good Morning Bri,   10:51 PM
I have pushed in.txt, expected_dos.txt & expected_out.txt to remote branch 58.  I have not pushed anything to master. (edited)

10:54 PM
However, the comparison makes it look like your changes to list.js for the ioopt issue did not happen.  Perhaps a pull / merge failure on my part.  Not sure.  I expect that we should work together on it.

10:58 PM
If I switch to master, run app.js and list internal, I see ioopt=3; If I set it to 5 and then list violations, I see only one line of output.  So, I expect that we also need to consider that your code repair was not effective or was not in my pull to my local master. (edited)

* * * * * * * * * * * * 
I just did a pull and repeated this test.  Same results.

**Comment by 1fifoto** [comment]
Here is the before output:

    
                                 P C y l
    
             A DECISION SUPPORT SYSTEM FOR PISTON/CYLINDER DESIGN
    
                          A product of Michael Milley
                   125 Jardin Dr.   Los Altos,  Ca.    94022
    
             Copyright 1990  Michael Milley    All rights reserved.
                           License agreement required.
    
                           VERSION 1.2
                       
    
         Please review the  RESTRICTIONS  section of the documentation.
         Validity, accuracy or applicability of results of this program are
         NOT guaranteed.  The user must verify all results by independent
         means and assume all responsibilities for their use and consequences.
         No warranty is provided.  No liability is assumed.
    
    START:
    ENTER NAME OF STARTUP FILE.
      (DEFAULT = STARTUP) : 
    RETAIN CURRENT INTERNAL VARIABLES & OPTIONS ?  (y/N) : 
    INTERNAL VARIABLES & OPTIONS HAVE BEEN SET.
    READING STARTUP FILE STARTUP.DSN ...
    PCyl: list int
    list int
    
    IOOPT  =   3            DEL    = 1.000000        FIX_WT  =   1.50
    MAXIT  = 100            DELMIN = 0.000100        CON_WT  =   1.00
    SEARCH =   1            TOL    = 0.000100        ZERO_WT =  10.00
    EQNSET =   1            OBJMIN = 0.000050        VIOL_WT =   1.00
                                                     MFN_WT  =   0.01
    PCyl: set ioopt 5
    set ioopt 5
    SET ...
    IOOPT has been set to: 5
    PCyl: list int
    list int
    INTERNAL VARIABLES
    
    IOOPT  =   5            DEL    = 1.000000        FIX_WT  =   1.50
    MAXIT  = 100            DELMIN = 0.000100        CON_WT  =   1.00
    SEARCH =   1            TOL    = 0.000100        ZERO_WT =  10.00
    EQNSET =   1            OBJMIN = 0.000050        VIOL_WT =   1.00
                                                     MFN_WT  =   0.01
    PCyl: list vio
    list vio
    CONSTRAINT VIOLATIONS
                            VALUE        LEVEL     DIFFERENCE    PERCENT
    FORCE           MIN     251.3274    1000.0000    748.6726     74.8673  VIOLATED
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.560511
    PCyl: quit
    quit
    QUITTING ...

Here is the after output:

    
                                 P C y l
    
             A DECISION SUPPORT SYSTEM FOR PISTON/CYLINDER DESIGN
    
                          A product of Michael Milley
                   125 Jardin Dr.   Los Altos,  Ca.    94022
    
             Copyright 1990  Michael Milley    All rights reserved.
                           License agreement required.
    
                           VERSION 1.2
                       
    
         Please review the  RESTRICTIONS  section of the documentation.
         Validity, accuracy or applicability of results of this program are
         NOT guaranteed.  The user must verify all results by independent
         means and assume all responsibilities for their use and consequences.
         No warranty is provided.  No liability is assumed.
    
    START:
    ENTER NAME OF STARTUP FILE.
      (DEFAULT = STARTUP) : 
    RETAIN CURRENT INTERNAL VARIABLES & OPTIONS ?  (y/N) : 
    INTERNAL VARIABLES & OPTIONS HAVE BEEN SET.
    READING STARTUP FILE STARTUP.DSN ...
    PCyl: list int
    list int
    IOOPT  =   3            DEL    = 1.000000        FIX_WT  =   1.50
    MAXIT  = 100            DELMIN = 0.000100        CON_WT  =   1.00
    SEARCH =   1            TOL    = 0.000100        ZERO_WT =  10.00
    EQNSET =   1            OBJMIN = 0.000050        VIOL_WT =   1.00
                                                     MFN_WT  =   0.01
    PCyl: set ioopt 5
    set ioopt 5
    SET ...
    IOOPT has been set to: 5
    PCyl: list int
    list int
    INTERNAL VARIABLES
    IOOPT  =   5            DEL    = 1.000000        FIX_WT  =   1.50
    MAXIT  = 100            DELMIN = 0.000100        CON_WT  =   1.00
    SEARCH =   1            TOL    = 0.000100        ZERO_WT =  10.00
    EQNSET =   1            OBJMIN = 0.000050        VIOL_WT =   1.00
                                                     MFN_WT  =   0.01
    PCyl: list vio
    list vio
    CONSTRAINT VIOLATIONS
                            VALUE        LEVEL     DIFFERENCE    PERCENT
    PRESSURE        MAX     500.0000    1500.0000   1000.0000    -66.6667  
    RADIUS          MIN       0.4000       0.0000      0.4000   -100.0000  
    RADIUS          MAX       0.4000       0.5000      0.1000    -20.0000  
    THICKNESS       MIN       0.0400       0.0000      0.0400   -100.0000  
    THICKNESS       MAX       0.0400       0.0500      0.0100    -20.0000  
    FORCE           MIN     251.3274    1000.0000    748.6726     74.8673  VIOLATED
    STRESS          MAX    2500.0000    3000.0000    500.0000    -16.6667  
    VALUE OF THE OBJECTIVE FUNCTION AT THIS POINT IS:              0.560511
    PCyl: quit
    quit
    QUITTING ...

**Comment by 1fifoto** [comment]
Merged into master, closing
