### ISSUE TITLE
Improve comment handling in save.js and start.js

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#86]
The PL/I code will echo a comment that is saved into the .DSN file.

The PL/I code will save a comment placed onto the SAVE command line into a .DSN file.  For example:
SAVE ABC THIS TEXT APPEARS ON THE COMMAND LINE

… will have the comment "THIS TEXT APPEARS ON THE COMMAND LINE" saved into the ABC.DSN file.  That text will be echoed the next time the ABC.DSN file is read.

**Comment by 1fifoto** [comment]
Modifications made to start and save. Start now displays the comment which is in the DSN file. Save now puts the comment in the DSN file.

For example, at initial load, it now includes the comment:

    START:
    ENTER NAME OF STARTUP FILE.
      (DEFAULT = STARTUP) : 
    RETAIN CURRENT INTERNAL VARIABLES & OPTIONS ?  (y/N) : 
    INTERNAL VARIABLES & OPTIONS HAVE BEEN SET.
    READING STARTUP FILE STARTUP.DSN ...
    COMMENT FIELD SAVED WITH THIS DESIGN IS:
    PCYL Default startup file ...
    PCyl:

During save it accepts a comment:

    PCyl: SAVE ABC THIS TEXT APPEARS ON THE COMMAND LINE
    SAVE ABC THIS TEXT APPEARS ON THE COMMAND LINE
    SAVE ...
    ABC.DSN IS COMPLETE
    PCyl: 

Later during start of this file it display the comment:

    PCyl: start abc
    start abc
    START:
    RETAIN CURRENT INTERNAL VARIABLES & OPTIONS ?  (y/N) : 
    INTERNAL VARIABLES & OPTIONS HAVE BEEN SET.
    READING STARTUP FILE ABC.DSN ...
    COMMENT FIELD SAVED WITH THIS DESIGN IS:
    THIS TEXT APPEARS ON THE COMMAND LINE
    PCyl:

Merged into master, awaiting your review before closing.

**Comment by grumpyinca** [comment]
Confirmed correct operation via in.txt and actual_out.txt.  Closing.
