### ISSUE TITLE
Investigate label handling.  Bug ?

### ISSUE THREAD

**Issue by grumpyinca** [thegrumpys/pcyl#88]
The SET confirms that a comment label is set.  However, the list label command does not print it.  Copy-Paste follows:

PCyl: set label comment this is the new comment by Mike
set label comment this is the new comment by Mike
SET ...
LABEL COMMENT HAS BEEN SET TO "THIS IS THE NEW COMMENT BY MIKE"
PCyl: li la
li la
LABEL:
CONTACT_PERSON 
COMPANY_NAME 
STREET 
CITY 
STATE_&_ZIP 
PHONE 
DATE 
PART_NUMBER 
FINISH 
COMMENT 
PCyl:

**Comment by 1fifoto** [comment]
This was mostly repaired as of issue 86, but I did add an ':' after each label name in this branch. Here is a sample initial start up followed by a list labels:

    START:
    ENTER NAME OF STARTUP FILE.
      (DEFAULT = STARTUP) : 
    RETAIN CURRENT INTERNAL VARIABLES & OPTIONS ?  (y/N) : 
    INTERNAL VARIABLES & OPTIONS HAVE BEEN SET.
    READING STARTUP FILE STARTUP.DSN ...
    COMMENT FIELD SAVED WITH THIS DESIGN IS:
    PCYL Default startup file ...
    PCyl: li la
    li la
    LABEL:
    CONTACT_PERSON: 
    COMPANY_NAME: 
    STREET: 
    CITY: 
    STATE_&_ZIP: 
    PHONE: 
    DATE: 
    PART_NUMBER: 
    FINISH: 
    COMMENT: PCYL Default startup file ...

Here is a later start of 'abc' DSN file followed by a list labels:

    PCyl: start abc
    start abc
    START:
    RETAIN CURRENT INTERNAL VARIABLES & OPTIONS ?  (y/N) : 
    INTERNAL VARIABLES & OPTIONS HAVE BEEN SET.
    READING STARTUP FILE ABC.DSN ...
    COMMENT FIELD SAVED WITH THIS DESIGN IS:
    THIS TEXT APPEARS ON THE COMMAND LINE
    PCyl: li la
    li la
    LABEL:
    CONTACT_PERSON: 
    COMPANY_NAME: 
    STREET: 
    CITY: 
    STATE_&_ZIP: 
    PHONE: 
    DATE: 
    PART_NUMBER: 
    FINISH: 
    COMMENT: THIS TEXT APPEARS ON THE COMMAND LINE
    PCyl:

Merged into master, awaiting your review to close it.

**Comment by 1fifoto** [comment]
One more update:

    PCyl: set label comment this is the new comment by Mike
    set label comment this is the new comment by Mike
    SET ...
    LABEL COMMENT HAS BEEN SET TO "THIS IS THE NEW COMMENT BY MIKE"
    PCyl: li la
    li la
    LABEL:
    CONTACT_PERSON: 
    COMPANY_NAME: 
    STREET: 
    CITY: 
    STATE_&_ZIP: 
    PHONE: 
    DATE: 
    PART_NUMBER: 
    FINISH: 
    COMMENT: THIS IS THE NEW COMMENT BY MIKE
    PCyl:

**Comment by grumpyinca** [comment]
Confirmed operation as desired.  Note, as a result of limitations on prompting, operation does not exactly match the operation of the PL/I code.  Closing.
